include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: warning
    prefer_const_constructors: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    prefer_final_locals: true
    prefer_const_declarations: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
