// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/media_scan.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1942300523;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'lumiluna_rust',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<bool> crateApiMediaScanExtractAudioCover(
      {required String path, required String outputPath});

  Future<bool> crateApiMediaScanExtractVideoCover(
      {required String path, required String outputPath, required int timeMs});

  Future<void> crateApiInitApp();

  Future<String> crateApiMediaScanPing();

  Future<List<RustMediaItem>> crateApiMediaScanScanMedia(
      {required List<String> folders, required int maxDepth, required String cacheDir});

  Future<List<RustMediaItem>> crateApiMediaScanScanMediaBatch(
      {required List<String> folders,
      required int maxDepth,
      required String cacheDir,
      required int offset,
      required int limit});

  Future<List<List<RustMediaItem>>> crateApiMediaScanScanMediaBatches(
      {required List<String> folders,
      required int maxDepth,
      required String cacheDir,
      required int batchSize});

  Future<BigInt> crateApiMediaScanStableFileHash(
      {required String path,
      required PlatformInt64 size,
      required PlatformInt64 modifiedMs});

  Future<BigInt> crateApiMediaScanStableHash({required String path});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiMediaScanExtractAudioCover(
      {required String path, required String outputPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(outputPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMediaScanExtractAudioCoverConstMeta,
      argValues: [path, outputPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMediaScanExtractAudioCoverConstMeta =>
      const TaskConstMeta(
        debugName: "extract_audio_cover",
        argNames: ["path", "outputPath"],
      );

  @override
  Future<bool> crateApiMediaScanExtractVideoCover(
      {required String path, required String outputPath, required int timeMs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(outputPath, serializer);
        sse_encode_u_32(timeMs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMediaScanExtractVideoCoverConstMeta,
      argValues: [path, outputPath, timeMs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMediaScanExtractVideoCoverConstMeta =>
      const TaskConstMeta(
        debugName: "extract_video_cover",
        argNames: ["path", "outputPath", "timeMs"],
      );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<String> crateApiMediaScanPing() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMediaScanPingConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMediaScanPingConstMeta => const TaskConstMeta(
        debugName: "ping",
        argNames: [],
      );

  @override
  Future<List<RustMediaItem>> crateApiMediaScanScanMedia(
      {required List<String> folders, required int maxDepth, required String cacheDir}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(folders, serializer);
        sse_encode_u_32(maxDepth, serializer);
        sse_encode_String(cacheDir, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_rust_media_item,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMediaScanScanMediaConstMeta,
      argValues: [folders, maxDepth, cacheDir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMediaScanScanMediaConstMeta => const TaskConstMeta(
        debugName: "scan_media",
        argNames: ["folders", "maxDepth", "cacheDir"],
      );

  @override
  Future<List<RustMediaItem>> crateApiMediaScanScanMediaBatch(
      {required List<String> folders,
      required int maxDepth,
      required String cacheDir,
      required int offset,
      required int limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(folders, serializer);
        sse_encode_u_32(maxDepth, serializer);
        sse_encode_String(cacheDir, serializer);
        sse_encode_u_32(offset, serializer);
        sse_encode_u_32(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_rust_media_item,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMediaScanScanMediaBatchConstMeta,
      argValues: [folders, maxDepth, cacheDir, offset, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMediaScanScanMediaBatchConstMeta =>
      const TaskConstMeta(
        debugName: "scan_media_batch",
        argNames: ["folders", "maxDepth", "cacheDir", "offset", "limit"],
      );

  @override
  Future<List<List<RustMediaItem>>> crateApiMediaScanScanMediaBatches(
      {required List<String> folders,
      required int maxDepth,
      required String cacheDir,
      required int batchSize}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(folders, serializer);
        sse_encode_u_32(maxDepth, serializer);
        sse_encode_String(cacheDir, serializer);
        sse_encode_u_32(batchSize, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_list_rust_media_item,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMediaScanScanMediaBatchesConstMeta,
      argValues: [folders, maxDepth, cacheDir, batchSize],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMediaScanScanMediaBatchesConstMeta =>
      const TaskConstMeta(
        debugName: "scan_media_batches",
        argNames: ["folders", "maxDepth", "cacheDir", "batchSize"],
      );

  @override
  Future<BigInt> crateApiMediaScanStableFileHash(
      {required String path,
      required PlatformInt64 size,
      required PlatformInt64 modifiedMs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_i_64(size, serializer);
        sse_encode_i_64(modifiedMs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMediaScanStableFileHashConstMeta,
      argValues: [path, size, modifiedMs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMediaScanStableFileHashConstMeta =>
      const TaskConstMeta(
        debugName: "stable_file_hash",
        argNames: ["path", "size", "modifiedMs"],
      );

  @override
  Future<BigInt> crateApiMediaScanStableHash({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMediaScanStableHashConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMediaScanStableHashConstMeta =>
      const TaskConstMeta(
        debugName: "stable_hash",
        argNames: ["path"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_32(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_f_64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<List<RustMediaItem>> dco_decode_list_list_rust_media_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_rust_media_item).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RustMediaItem> dco_decode_list_rust_media_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_media_item).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  RustMediaItem dco_decode_rust_media_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 26)
      throw Exception('unexpected arr length: expect 26 but see ${arr.length}');
    return RustMediaItem(
      path: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      mediaType: dco_decode_String(arr[2]),
      size: dco_decode_i_64(arr[3]),
      modifiedMs: dco_decode_i_64(arr[4]),
      fileHash: dco_decode_u_64(arr[5]),
      title: dco_decode_opt_String(arr[6]),
      artist: dco_decode_opt_String(arr[7]),
      album: dco_decode_opt_String(arr[8]),
      durationMs: dco_decode_opt_box_autoadd_i_64(arr[9]),
      artworkPath: dco_decode_opt_String(arr[10]),
      thumbnailPath: dco_decode_opt_String(arr[11]),
      imageWidth: dco_decode_opt_box_autoadd_i_32(arr[12]),
      imageHeight: dco_decode_opt_box_autoadd_i_32(arr[13]),
      imageDateTaken: dco_decode_opt_String(arr[14]),
      imageCameraMake: dco_decode_opt_String(arr[15]),
      imageCameraModel: dco_decode_opt_String(arr[16]),
      imageGpsLat: dco_decode_opt_box_autoadd_f_64(arr[17]),
      imageGpsLng: dco_decode_opt_box_autoadd_f_64(arr[18]),
      imageIso: dco_decode_opt_box_autoadd_i_32(arr[19]),
      imageFocalLength: dco_decode_opt_box_autoadd_f_64(arr[20]),
      imageFNumber: dco_decode_opt_box_autoadd_f_64(arr[21]),
      videoWidth: dco_decode_opt_box_autoadd_i_32(arr[22]),
      videoHeight: dco_decode_opt_box_autoadd_i_32(arr[23]),
      videoCodec: dco_decode_opt_String(arr[24]),
      videoFps: dco_decode_opt_box_autoadd_f_64(arr[25]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<List<RustMediaItem>> sse_decode_list_list_rust_media_item(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <List<RustMediaItem>>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_rust_media_item(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RustMediaItem> sse_decode_list_rust_media_item(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <RustMediaItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_media_item(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RustMediaItem sse_decode_rust_media_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_path = sse_decode_String(deserializer);
    final var_name = sse_decode_String(deserializer);
    final var_mediaType = sse_decode_String(deserializer);
    final var_size = sse_decode_i_64(deserializer);
    final var_modifiedMs = sse_decode_i_64(deserializer);
    final var_fileHash = sse_decode_u_64(deserializer);
    final var_title = sse_decode_opt_String(deserializer);
    final var_artist = sse_decode_opt_String(deserializer);
    final var_album = sse_decode_opt_String(deserializer);
    final var_durationMs = sse_decode_opt_box_autoadd_i_64(deserializer);
    final var_artworkPath = sse_decode_opt_String(deserializer);
    final var_thumbnailPath = sse_decode_opt_String(deserializer);
    final var_imageWidth = sse_decode_opt_box_autoadd_i_32(deserializer);
    final var_imageHeight = sse_decode_opt_box_autoadd_i_32(deserializer);
    final var_imageDateTaken = sse_decode_opt_String(deserializer);
    final var_imageCameraMake = sse_decode_opt_String(deserializer);
    final var_imageCameraModel = sse_decode_opt_String(deserializer);
    final var_imageGpsLat = sse_decode_opt_box_autoadd_f_64(deserializer);
    final var_imageGpsLng = sse_decode_opt_box_autoadd_f_64(deserializer);
    final var_imageIso = sse_decode_opt_box_autoadd_i_32(deserializer);
    final var_imageFocalLength = sse_decode_opt_box_autoadd_f_64(deserializer);
    final var_imageFNumber = sse_decode_opt_box_autoadd_f_64(deserializer);
    final var_videoWidth = sse_decode_opt_box_autoadd_i_32(deserializer);
    final var_videoHeight = sse_decode_opt_box_autoadd_i_32(deserializer);
    final var_videoCodec = sse_decode_opt_String(deserializer);
    final var_videoFps = sse_decode_opt_box_autoadd_f_64(deserializer);
    return RustMediaItem(
        path: var_path,
        name: var_name,
        mediaType: var_mediaType,
        size: var_size,
        modifiedMs: var_modifiedMs,
        fileHash: var_fileHash,
        title: var_title,
        artist: var_artist,
        album: var_album,
        durationMs: var_durationMs,
        artworkPath: var_artworkPath,
        thumbnailPath: var_thumbnailPath,
        imageWidth: var_imageWidth,
        imageHeight: var_imageHeight,
        imageDateTaken: var_imageDateTaken,
        imageCameraMake: var_imageCameraMake,
        imageCameraModel: var_imageCameraModel,
        imageGpsLat: var_imageGpsLat,
        imageGpsLng: var_imageGpsLng,
        imageIso: var_imageIso,
        imageFocalLength: var_imageFocalLength,
        imageFNumber: var_imageFNumber,
        videoWidth: var_videoWidth,
        videoHeight: var_videoHeight,
        videoCodec: var_videoCodec,
        videoFps: var_videoFps);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_rust_media_item(
      List<List<RustMediaItem>> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_rust_media_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_rust_media_item(
      List<RustMediaItem> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_media_item(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_rust_media_item(
      RustMediaItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.mediaType, serializer);
    sse_encode_i_64(self.size, serializer);
    sse_encode_i_64(self.modifiedMs, serializer);
    sse_encode_u_64(self.fileHash, serializer);
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.artist, serializer);
    sse_encode_opt_String(self.album, serializer);
    sse_encode_opt_box_autoadd_i_64(self.durationMs, serializer);
    sse_encode_opt_String(self.artworkPath, serializer);
    sse_encode_opt_String(self.thumbnailPath, serializer);
    sse_encode_opt_box_autoadd_i_32(self.imageWidth, serializer);
    sse_encode_opt_box_autoadd_i_32(self.imageHeight, serializer);
    sse_encode_opt_String(self.imageDateTaken, serializer);
    sse_encode_opt_String(self.imageCameraMake, serializer);
    sse_encode_opt_String(self.imageCameraModel, serializer);
    sse_encode_opt_box_autoadd_f_64(self.imageGpsLat, serializer);
    sse_encode_opt_box_autoadd_f_64(self.imageGpsLng, serializer);
    sse_encode_opt_box_autoadd_i_32(self.imageIso, serializer);
    sse_encode_opt_box_autoadd_f_64(self.imageFocalLength, serializer);
    sse_encode_opt_box_autoadd_f_64(self.imageFNumber, serializer);
    sse_encode_opt_box_autoadd_i_32(self.videoWidth, serializer);
    sse_encode_opt_box_autoadd_i_32(self.videoHeight, serializer);
    sse_encode_opt_String(self.videoCodec, serializer);
    sse_encode_opt_box_autoadd_f_64(self.videoFps, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
