// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `media_type`, `read_audio_metadata`, `walk`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Future<String> ping() => RustLib.instance.api.crateApiMediaScanPing();

Future<BigInt> stableHash({required String path}) =>
    RustLib.instance.api.crateApiMediaScanStableHash(path: path);

Future<BigInt> stableFileHash(
        {required String path,
        required PlatformInt64 size,
        required PlatformInt64 modifiedMs}) =>
    RustLib.instance.api.crateApiMediaScanStableFileHash(
        path: path, size: size, modifiedMs: modifiedMs);

Future<bool> extractAudioCover(
        {required String path, required String outputPath}) =>
    RustLib.instance.api
        .crateApiMediaScanExtractAudioCover(path: path, outputPath: outputPath);

Future<bool> extractVideoCover(
        {required String path,
        required String outputPath,
        required int timeMs}) =>
    RustLib.instance.api.crateApiMediaScanExtractVideoCover(
        path: path, outputPath: outputPath, timeMs: timeMs);

Future<List<RustMediaItem>> scanMedia(
        {required List<String> folders,
        required int maxDepth,
        required String cacheDir,
        required String existingHashesJson}) =>
    RustLib.instance.api.crateApiMediaScanScanMedia(
        folders: folders, maxDepth: maxDepth, cacheDir: cacheDir, existingHashesJson: existingHashesJson);

Future<List<RustMediaItem>> scanMediaBatch(
        {required List<String> folders,
        required int maxDepth,
        required String cacheDir,
        required String existingHashesJson,
        required int offset,
        required int limit}) =>
    RustLib.instance.api.crateApiMediaScanScanMediaBatch(
        folders: folders,
        maxDepth: maxDepth,
        cacheDir: cacheDir,
        existingHashesJson: existingHashesJson,
        offset: offset,
        limit: limit);

Future<List<List<RustMediaItem>>> scanMediaBatches(
        {required List<String> folders,
        required int maxDepth,
        required String cacheDir,
        required String existingHashesJson,
        required int batchSize}) =>
    RustLib.instance.api.crateApiMediaScanScanMediaBatches(
        folders: folders, maxDepth: maxDepth, cacheDir: cacheDir, existingHashesJson: existingHashesJson, batchSize: batchSize);

class RustMediaItem {
  final String path;
  final String name;
  final String mediaType;
  final PlatformInt64 size;
  final PlatformInt64 modifiedMs;
  final BigInt fileHash;
  final String? title;
  final String? artist;
  final String? album;
  final PlatformInt64? durationMs;
  final String? artworkPath;
  final String? thumbnailPath;
  final int? imageWidth;
  final int? imageHeight;
  final String? imageDateTaken;
  final String? imageCameraMake;
  final String? imageCameraModel;
  final double? imageGpsLat;
  final double? imageGpsLng;
  final int? imageIso;
  final double? imageFocalLength;
  final double? imageFNumber;
  final int? videoWidth;
  final int? videoHeight;
  final String? videoCodec;
  final double? videoFps;

  const RustMediaItem({
    required this.path,
    required this.name,
    required this.mediaType,
    required this.size,
    required this.modifiedMs,
    required this.fileHash,
    this.title,
    this.artist,
    this.album,
    this.durationMs,
    this.artworkPath,
    this.thumbnailPath,
    this.imageWidth,
    this.imageHeight,
    this.imageDateTaken,
    this.imageCameraMake,
    this.imageCameraModel,
    this.imageGpsLat,
    this.imageGpsLng,
    this.imageIso,
    this.imageFocalLength,
    this.imageFNumber,
    this.videoWidth,
    this.videoHeight,
    this.videoCodec,
    this.videoFps,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      mediaType.hashCode ^
      size.hashCode ^
      modifiedMs.hashCode ^
      fileHash.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      durationMs.hashCode ^
      artworkPath.hashCode ^
      thumbnailPath.hashCode ^
      imageWidth.hashCode ^
      imageHeight.hashCode ^
      imageDateTaken.hashCode ^
      imageCameraMake.hashCode ^
      imageCameraModel.hashCode ^
      imageGpsLat.hashCode ^
      imageGpsLng.hashCode ^
      imageIso.hashCode ^
      imageFocalLength.hashCode ^
      imageFNumber.hashCode ^
      videoWidth.hashCode ^
      videoHeight.hashCode ^
      videoCodec.hashCode ^
      videoFps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustMediaItem &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          mediaType == other.mediaType &&
          size == other.size &&
          modifiedMs == other.modifiedMs &&
          fileHash == other.fileHash &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          durationMs == other.durationMs &&
          artworkPath == other.artworkPath &&
          thumbnailPath == other.thumbnailPath &&
          imageWidth == other.imageWidth &&
          imageHeight == other.imageHeight &&
          imageDateTaken == other.imageDateTaken &&
          imageCameraMake == other.imageCameraMake &&
          imageCameraModel == other.imageCameraModel &&
          imageGpsLat == other.imageGpsLat &&
          imageGpsLng == other.imageGpsLng &&
          imageIso == other.imageIso &&
          imageFocalLength == other.imageFocalLength &&
          imageFNumber == other.imageFNumber &&
          videoWidth == other.videoWidth &&
          videoHeight == other.videoHeight &&
          videoCodec == other.videoCodec &&
          videoFps == other.videoFps;
}
